feat(DEV-11277): Iframe app elements
team-monite/monite-sdk pull request #121
Opened 2024-06-17 18:17 UTC by vkuprin

2024-06-17 22:55 UTC, vkuprin commented on packages/sdk-iframe/src/iframe-app.tsx
> +        const id = await getEntityId(config.api_url, fetchToken);
Maybe makes sense to refactor to react-query, not sure... @radist2s
```ts
const useEntityId = (
  apiUrl: string,
  fetchToken: () => Promise<{
    access_token: string;
    token_type: string;
    expires_in: number;
  }>
) => {
  return useQuery(['entityId', apiUrl], () => getEntityId(apiUrl, fetchToken));
};
```

2024-06-19 11:48 UTC, vkuprin commented on packages/sdk-drop-in/src/common-app-element.tsx
> +      this.reactAppRoot.render(
document.create Element

2024-06-20 18:53 UTC, radist2s requested changes

2024-06-20 18:53 UTC, radist2s commented on packages/sdk-drop-in/index.html
> +      name-prop="dropIn"
`name-prop` probably is not needed anymore.

2024-06-20 18:53 UTC, radist2s commented on packages/sdk-drop-in/monite-iframe-app-consumer.html
> +      async function fetchAuthToken() {
Could you please remove not used with which marked with `// not used`?

2024-06-20 18:53 UTC, radist2s commented on packages/sdk-drop-in/monite-iframe-app.html
> +      // not used
Would be cool to remove garbage code from this file too `// not used`

2024-07-01 16:45 UTC, closed without merging