feat(DEV-9444): Demo theming  - add css classes to all react components
team-monite/monite-sdk pull request #207
Opened 2024-07-30 09:15 UTC by chebum

This PR adds class names to components that allow writing CSS selectors for demo theming.

2024-07-30 18:15 UTC, saladNights requested changes

2024-07-30 18:26 UTC, saladNights requested changes

2024-07-30 18:26 UTC, saladNights commented on packages/sdk-react/src/components/payables/Payables.tsx
> +  const className = 'Monite-Monite-Payables-Header';
duplication `Monite-`

2024-07-30 18:26 UTC, saladNights commented on packages/sdk-react/src/ui/SearchField/SearchField.tsx
> +export const SearchField = ({ label, onChange }: Props): React.ReactElement => {
type ReactElement is redundant

2024-07-31 08:38 UTC, chebum reviewed
Code modified as requested

2024-07-31 09:22 UTC, saladNights approved these changes

2024-07-31 12:07 UTC, merged