feat(DEV-12231) receivables custom tabs
team-monite/monite-sdk pull request #249
Opened 2024-08-16 13:54 UTC by radist2s

2024-08-19 07:26 UTC, hkosova requested changes

2024-08-19 07:26 UTC, hkosova commented on packages/sdk-react/src/components/receivables/ReceivablesTable/ReceivablesTable.stories.tsx
> +                        'declined',
```suggestion
                        'issued',
                        'overdue',
```
`accepted`, `declined`, and `expired` are quote statuses.

2024-08-19 07:26 UTC, hkosova commented on packages/sdk-react/src/components/receivables/ReceivablesTable/ReceivablesTable.tsx
> + *                 'declined',
```suggestion
 *                 'issued',               // only contain the values specified in "status__in"
 *                 'overdue',
```

2024-08-19 19:08 UTC, radist2s commented
@hkosova, could I ask you to validate the [status machine](https://github.com/team-monite/monite-sdk/blob/1c73f0fc9e81d3ab84143aec9a0df57a693afc6a/packages/sdk-react/src/components/receivables/ReceivableFilters/useReceivablesFilters.tsx#L57-L104)?

2024-08-20 06:30 UTC, hkosova commented
> could I ask you to validate the [status machine](https://github.com/team-monite/monite-sdk/blob/1c73f0fc9e81d3ab84143aec9a0df57a693afc6a/packages/sdk-react/src/components/receivables/ReceivableFilters/useReceivablesFilters.tsx#L57-L104)?

@radist2s LGTM

2024-09-23 12:45 UTC, merged