fix(DEV-12336): fix table filters layout and make them responsive
team-monite/monite-sdk pull request #261
Opened 2024-08-21 09:44 UTC by chebum

This PR fixes layout of table filters

2024-08-21 09:58 UTC, chebum commented on packages/sdk-themes/src/themes/monite.ts
> +          '& > *': {
@radist2s I made this changes in theme itself, but the filters will look worse in the blank Material UI theme. I can move the layout styles to the sdk itself.

2024-08-22 13:22 UTC, radist2s requested changes

2024-08-22 13:22 UTC, radist2s commented on packages/sdk-react/src/components/approvalRequests/ApprovalRequestsTable/ApprovalRequestsFilter/ApprovalRequestsFilter.tsx
> -    <Grid container justifyContent="space-between">
The same advice: would be better using just css to pull elements to the right.

2024-08-22 13:22 UTC, radist2s commented on packages/sdk-react/src/components/counterparts/CounterpartsTable/Filters/Filters.tsx
> -              onChangeFilter(FILTER_TYPE_TYPE, search.target.value);
As I see, this refactoring with the selectors `onChangeFilter` and `value`s should be a part for separate PR. Moreover, this refactoring the code without need adds difficulties for other developers on merges.
Btw, I would not change options to `'false' | 'true'`

2024-08-27 10:26 UTC, vkuprin commented on packages/sdk-react/src/components/misc/FilterContainer.tsx
> +interface Props {
We have a convention to name them as `ComponentNameProps`, so in this case `FilterContainerProps`

2024-08-27 15:00 UTC, vkuprin approved these changes

2024-08-27 15:17 UTC, merged